### ISSUE TITLE
Add Heat Maps (see Comment)

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#28]
Add analytics to view where there are current push notifications

**Comment by bmwhiteh** [comment]
Show where Push Notifications have been sent out

**Comment by bmwhiteh** [comment]
1. Push Notifications
2. Fitness Activities
3. Geolocation

**Comment by andreamoorman** [comment]
The weather API searches for any alerts in Fort Wayne, so I don't think we'll need to have one for push notifications because it would just be the same color all over
