### ISSUE TITLE
Add Heat Map for Geolocation Data (Delete)

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#30]
Add analytics for viewing current users map

**Comment by bmwhiteh** [comment]
This page will open up a Google Map with a Heat map overlay of all the users locations that have been entered.

**Comment by bmwhiteh** [comment]
All activities tracked in the mobile app should store geolocation data from Point A to Point B. The goal of this map is to show this data as a heat map displaying use of the trails. Location masking problems can cause this heat map to show incorrect data.
