### ISSUE TITLE
Add Users Database table

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#31]
Table should have the following attributes:
Id
Username
Password (encrypted)
Email
Age
Weight
Height
Gender
Activities Tracked
Tickets Tracked
Able to Send Picture Tickets
Receive Push Notifications
strZipCode

**Comment by bmwhiteh** [comment]
Table: users
Column:
- intUserId int(10) PRIMARY
- strUsername varchar(20)
- strEncryptedPassword varchar(40)
- strEmailAddress varchar(40)
- intAge int(5)
- intWeight int(5)
- intHeight int(5)
- strGender varchar(10)
- strActivitiesTracked text
- strTicketsTracked text
- bitSendPictures bit(2)
- bitReceiveNotifications bit(2)
- intZipCode int(10)
- dtStartDate date
