### ISSUE TITLE
Add Tickets Database Table

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#32]
Add a database table named Tickets. This table should have the following attributes:
strUserID
dtTicketsOpened
strTicketDiscription
imgTicketImageFilePath
dtTicketClosed
strTicketType
bitUrgent

**Comment by bmwhiteh** [comment]
Table: tickets
Columns:
- intUserId int PRIMARY
- dtTicketOpen date
- dtTicketClose date
- strImageFilePath text
- strDescription text
- strType varchar(30)
- bitUrgent bit(2)
