### ISSUE TITLE
Add Push Notifications Database table

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#33]
Add a Push Notifications Database Table.  
This table should have the following attributes:

dtSent
intUsersSentTo
strJSONmessage

**Comment by bmwhiteh** [comment]
Table: pushNotifications
Columns:
- intPushId int(11) PRIMARY
- dtSentToMobile date
- dtReceivedFromAPI date
- intUsersSentTo int(11)
- strJSONMessage text
- strNotificationType varchar(10)

**Comment by bmwhiteh** [comment]
Initial page setup is done. Just need better CSS and content.
