### ISSUE TITLE
Conversion from .NET to PHP (Web Server)

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#36]
Install a PHP oriented web server on the City Server

**Comment by bmwhiteh** [comment]
This is strange. And I feel it deserves an explanation. It seems that the IIS Manager is able to have both PHP and ASP.NET installed and used on separate sites. I was able to create a localhost site that when browsed in the IIS manager did pull up the default php file I had set in the empty folder I made for our project. Further testing with pages is needed.
