### ISSUE TITLE
Add Scheduled Tasks Page

### ISSUE THREAD

**Issue by andreamoorman** [bmwhiteh/GreenwayProject_AdminPortal#5]
Conversion of Scheduled Tasks Page to HTML5/PHP

**Comment by bmwhiteh** [comment]
This page will be used to display and run any scheduled tasks, the Admin Portal or mobile app must run on a daily, monthly, or yearly to keep the databases, reports, etc. running smoothly. HTML5 needs a suitable layout for displaying a list of query results and possibly a form allowing the user to run a specific task.
